type Tab='hot'|'write'|'prompt'|'contest'|'tools'|'global';
type Trend={rank?:number;community?:string;source_title?:string;url?:string;topic?:string;summary?:string;why_trending?:string;x_angle?:string;x_hook?:string};
type TrendData={generated_at?:string;items?:Trend[]};
type Visitors={active:number|null;today:number|null;total:number|null;available?:boolean};
type Paper={id?:string;title?:string;summary?:string;publishedAt?:string;upvotes?:number;numComments?:number;githubRepo?:string;organization?:{fullname?:string;name?:string}};
type Daily=Paper&{paper?:Paper};

const TOP='luna-signal-top-nav',MOBILE='luna-mobile-nav',STYLE='luna-signal-shell-style',WRITE='luna-signal-write-root',TOOLS='luna-signal-tools-root',GLOBAL='luna-signal-global-root',VISITORS='luna-signal-visitor-bar';
const TABS:Array<[Tab,string,string]>=[['hot','핫이슈','◉'],['write','오늘 뭐 쓰지?','✎'],['prompt','프롬프트 스튜디오','✦'],['contest','공모전','◆'],['tools','크리에이터 툴','⬡'],['global','글로벌 시그널','↗']];
const TOOL_LINKS:Array<[string,string,string]>=[['Seedance','숏폼 영상','https://seed.bytedance.com/en/seedance'],['Google Flow','Veo 장면 제작','https://labs.google/fx/tools/flow'],['Runway','생성형 영상 편집','https://runwayml.com'],['Kling AI','이미지 기반 영상','https://klingai.com'],['Krea','실시간 이미지 생성','https://krea.ai'],['Ideogram','타이포 이미지','https://ideogram.ai'],['Hugging Face Spaces','AI 앱 탐색','https://huggingface.co/spaces'],['Product Hunt','새 서비스 발견','https://www.producthunt.com'],['GitHub Trending','급상승 오픈소스','https://github.com/trending'],['Perplexity','출처 기반 리서치','https://www.perplexity.ai'],['Cursor','AI 코딩','https://cursor.com'],['Vercel','웹앱 배포','https://vercel.com']];
let active:Tab=isTab(location.hash.slice(1))?location.hash.slice(1) as Tab:'hot',drafts:string[]=[],writeReady=false,globalReady=false,watcher:MutationObserver|null=null,busy=false,timer:number|null=null;
const q=<T extends Element>(s:string,r:ParentNode=document)=>r.querySelector<T>(s);
const qa=<T extends Element>(s:string,r:ParentNode=document)=>Array.from(r.querySelectorAll<T>(s));
function isTab(v:string|null):v is Tab{return TABS.some(([k])=>k===v)}
function e(v:unknown){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function n(v:number|null|undefined){return typeof v==='number'?new Intl.NumberFormat('ko-KR').format(v):'확인 불가'}
function d(v?:string){const x=v?new Date(v):null;return x&&!Number.isNaN(x.getTime())?new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(x):'시간 확인 불가'}
function cut(v?:string,max=190){const x=(v??'').replace(/\s+/g,' ').trim();return x.length>max?`${x.slice(0,max).trim()}…`:x}
function navButtons(mobile=false){return TABS.map(([k,l,i])=>`<button type="button" data-signal-tab="${k}" aria-pressed="false">${mobile?`<span>${i}</span>`:''}<b>${l}</b></button>`).join('')}

function styles(){if(q(`#${STYLE}`))return;const s=document.createElement('style');s.id=STYLE;s.textContent=`
.signalBrand{margin:0!important;line-height:.8!important}.signalBrand .luna{display:block;color:#7769e7;font:italic 700 clamp(38px,4vw,56px) Georgia,serif}.signalBrand .signal{display:inline-block;color:transparent;background:linear-gradient(110deg,#6f63ff,#8fd8ff,#d6b7ff,#fff7d9,#8ff0d0,#ffb7dd,#786cff);background-size:260% 100%;-webkit-background-clip:text;background-clip:text;font-size:clamp(60px,7vw,98px);font-weight:950;filter:drop-shadow(0 8px 18px rgba(112,92,200,.18));animation:aurora 8s ease-in-out infinite}@keyframes aurora{50%{background-position:100%}}
.signalTop{position:sticky;top:10px;z-index:9000;display:flex;justify-content:center;gap:6px;width:min(1120px,calc(100% - 12px));margin:0 auto 25px;padding:8px;border:1px solid #e5e0f2;border-radius:20px;background:#fffffff0;box-shadow:0 14px 38px #2c235217;backdrop-filter:blur(18px);overflow-x:auto}.signalTop button{flex:none;min-height:45px;padding:0 17px;border:0;border-radius:13px;background:transparent;color:#736c82;font-weight:850;white-space:nowrap}.signalTop button.active{background:#211d35;color:#fff}
.signalPanel{width:min(1120px,calc(100% - 32px));margin:0 auto 42px;padding:28px;border:1px solid #e3dff0;border-radius:28px;background:#fffffff2;box-shadow:0 22px 62px #2d265315}.signalHead{display:flex;justify-content:space-between;gap:16px;align-items:end;margin-bottom:19px}.signalHead small,.signalCard>small{color:#7259b4;font-weight:950;letter-spacing:.1em}.signalHead h2{margin:6px 0 0;font-size:clamp(28px,4vw,42px);letter-spacing:-.045em}.signalHead p,.signalCard p{margin:7px 0 0;color:#696374;line-height:1.65}.signalMeta{padding:8px 11px;border-radius:999px;background:#f0edf8;color:#675d7b;font-size:11px;font-weight:850;white-space:nowrap}.signalGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.signalCard{display:flex;flex-direction:column;padding:19px;border:1px solid #e8e4f1;border-radius:20px;background:#fff}.signalCard h3{margin:9px 0 5px;font-size:18px;line-height:1.4}.signalBox{margin-top:11px;padding:11px;border-radius:13px;background:#f7f5fb}.signalBox b{display:block;margin-bottom:4px;color:#796f90;font-size:9px;letter-spacing:.1em}.signalBox p{white-space:pre-line;font-size:13px}.signalActions{display:flex;gap:8px;margin-top:auto;padding-top:14px}.signalActions a,.signalActions button{flex:1;display:grid;place-items:center;min-height:39px;border:1px solid #ddd6ea;border-radius:10px;background:#fff;color:#514768;text-decoration:none;font-size:12px;font-weight:900}.signalActions button{background:#211d35;color:#fff}.signalState{display:grid;place-items:center;min-height:180px;border:1px dashed #cfc7e2;border-radius:19px;text-align:center;color:#6f6882}.signalState strong{display:block;color:#28233d;font-size:18px}.signalState button{margin-top:9px;padding:9px 13px;border:0;border-radius:10px;background:#211d35;color:#fff;font-weight:900}.signalTools{display:grid;grid-template-columns:repeat(4,1fr);gap:11px}.signalTool{padding:16px;border:1px solid #e8e4f1;border-radius:17px;background:#fff;color:inherit;text-decoration:none}.signalTool small{color:#7259b4;font-weight:950}.signalTool strong{display:block;margin:7px 0}.signalTool p{margin:0;color:#756e80;font-size:12px}.signalVisitors{grid-column:2;display:grid;grid-template-columns:1fr 1px 1fr;gap:13px;align-items:center;margin-top:-19px;padding:12px 17px;border:1px solid #e3dff0;border-radius:17px;background:#fffffff0}.signalVisitors .line{height:27px;background:#ddd8ef}.signalStat{display:flex;justify-content:center;align-items:center;gap:8px}.signalStat i{width:7px;height:7px;border-radius:50%;background:#63d6ac;box-shadow:0 0 0 5px #63d6ac21}.signalStat small{display:block;color:#817b91;font-size:10px;font-weight:850}.signalStat strong{display:block;font-size:17px}.trendRadarHook,.trendRadarAngle,.trendRadarActions button,.trendRadarListMeta button,.trendRadarVisitorBadge{display:none!important}.lunaMobileNav button.active{background:linear-gradient(135deg,#e5deff,#dcf5ff)!important;color:#2d2450!important}
@media(max-width:1024px){.signalTop{justify-content:flex-start;width:calc(100% - 20px)}.signalTop button{padding:0 13px;font-size:13px}.signalPanel{width:calc(100% - 16px);padding:21px 15px}.signalGrid{grid-template-columns:1fr}.signalTools{grid-template-columns:repeat(2,1fr)}.signalVisitors{grid-column:1;margin-top:-8px}.lunaMobileNav{grid-template-columns:repeat(6,1fr)!important}}@media(max-width:560px){.signalHead{display:block}.signalMeta{display:inline-block;margin-top:9px}.signalTools{grid-template-columns:1fr}.signalActions{flex-direction:column}.signalBrand .signal{font-size:56px}}@media(prefers-reduced-motion:reduce){.signalBrand .signal{animation:none}}`;document.head.appendChild(s)}
function hero(main:HTMLElement){const badge=q<HTMLElement>('.heroCopy .badge',main);if(badge)badge.textContent='CREATOR SIGNAL · ASTRYX Y2K THEME';const title=q<HTMLElement>('.heroCopy h1',main);if(title&&!q('.signal',title)){title.className='signalBrand';title.setAttribute('aria-label','Luna Signal');title.innerHTML='<span class="luna">Luna</span><span class="signal">Signal</span>'}const lead=q<HTMLElement>('.heroCopy .lead',main);if(lead&&lead.dataset.signalCopy!=='1'){lead.dataset.signalCopy='1';lead.innerHTML='프롬프트 제작부터 핫이슈 탐색, 공모전 발견까지.<br>콘텐츠 제작에 필요한 신호를 한곳에서 확인하세요.'}}
function tabNav(heroGrid:HTMLElement){let top=q<HTMLElement>(`#${TOP}`);if(!top){top=document.createElement('nav');top.id=TOP;top.className='signalTop';top.innerHTML=navButtons();top.setAttribute('aria-label','Luna Signal 메뉴');heroGrid.after(top);top.addEventListener('click',clickTab)}let mobile=q<HTMLElement>(`#${MOBILE}`);if(!mobile){mobile=document.createElement('nav');mobile.id=MOBILE;mobile.className='lunaMobileNav';document.body.appendChild(mobile);document.body.classList.add('hasLunaMobileNav')}if(mobile.dataset.signal!=='1'){mobile.dataset.signal='1';mobile.innerHTML=navButtons(true);mobile.addEventListener('click',clickTab)}return top}
function head(k:string,t:string,p:string,m:string){return `<header class="signalHead"><div><small>${k}</small><h2>${t}</h2><p>${p}</p></div>${m}</header>`}
function panel(id:string,group:Tab,html:string){const x=document.createElement('section');x.id=id;x.className='signalPanel';x.dataset.signalGroup=group;x.innerHTML=html;return x}
function custom(top:HTMLElement){let w=q<HTMLElement>(`#${WRITE}`);if(!w){w=panel(WRITE,'write',`${head('X CONTENT DESK','오늘 뭐 쓰지?','수집된 원문을 바탕으로 바로 쓸 수 있는 초안을 정리합니다.','<span class="signalMeta" data-write-meta>연결 전</span>')}<div class="signalState" data-write-state><div><strong>글감을 기다리고 있어요</strong><p>탭을 열면 불러옵니다.</p></div></div>`);top.after(w);w.addEventListener('click',writeClick)}let t=q<HTMLElement>(`#${TOOLS}`);if(!t){t=panel(TOOLS,'tools',`${head('CREATOR TOOLBOX','크리에이터 툴','공식 사이트로 바로 이동합니다.','')}<div class="signalTools">${TOOL_LINKS.map(([a,b,c])=>`<a class="signalTool" href="${c}" target="_blank" rel="noreferrer"><small>OFFICIAL</small><strong>${a}</strong><p>${b}</p></a>`).join('')}</div>`);w.after(t)}let g=q<HTMLElement>(`#${GLOBAL}`);if(!g){g=panel(GLOBAL,'global',`${head('GLOBAL AI SIGNALS','글로벌 시그널','Hugging Face Daily Papers 최신 자료를 불러옵니다.','<span class="signalMeta" data-global-meta>연결 전</span>')}<div class="signalState" data-global-state><div><strong>최신 자료를 기다리고 있어요</strong><p>탭을 열면 불러옵니다.</p></div></div>`);t.after(g);g.addEventListener('click',globalClick)}}
function visitor(heroGrid:HTMLElement){if(q(`#${VISITORS}`))return;const x=document.createElement('section');x.id=VISITORS;x.className='signalVisitors';x.hidden=true;x.innerHTML='<div class="signalStat"><i></i><div><small>지금 접속 중</small><strong data-active></strong></div></div><div class="line"></div><div class="signalStat"><div><small data-today></small><strong data-total></strong></div></div>';heroGrid.appendChild(x)}
function classify(main:HTMLElement){for(const node of Array.from(main.children)){const x=node as HTMLElement;if(x.classList.contains('heroGrid')||x.id===TOP){delete x.dataset.signalGroup;x.hidden=false;continue}if([WRITE,TOOLS,GLOBAL].includes(x.id))continue;x.dataset.signalGroup=x.id==='luna-trend-radar-root'?'hot':x.id==='contest-radar-root'||x.classList.contains('contestRadarRoot')?'contest':'prompt'}}
function show(tab:Tab,scroll=true){active=tab;history.replaceState(null,'',`${location.pathname}${location.search}#${tab}`);const main=q<HTMLElement>('main.page');if(main)classify(main);qa<HTMLElement>('[data-signal-group]').forEach(x=>x.hidden=x.dataset.signalGroup!==tab);qa<HTMLButtonElement>('[data-signal-tab]').forEach(b=>{const on=b.dataset.signalTab===tab;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))});const live=q<HTMLElement>('.trendRadarLive');if(live&&live.dataset.signal!=='1'){live.dataset.signal='1';live.innerHTML='<i></i> LATEST SCAN'}if(tab==='write')void loadWrite();if(tab==='global')void loadGlobal();if(scroll)requestAnimationFrame(()=>q(`#${TOP}`)?.scrollIntoView({behavior:'smooth',block:'start'}))}
function clickTab(ev:Event){const b=(ev.target as HTMLElement).closest<HTMLButtonElement>('[data-signal-tab]'),v=b?.dataset.signalTab??null;if(isTab(v))show(v)}
function ask(x:Trend){return `${(x.topic||x.source_title||'이 주제').replace(/[.?!]+$/,'')}, 여러분 생각은 어때요?`}
function makeDraft(x:Trend){return[x.x_hook||x.source_title,x.summary,x.why_trending,ask(x)].filter(Boolean).join('\n\n')}
async function loadWrite(force=false){if(writeReady&&!force)return;const root=q<HTMLElement>(`#${WRITE}`),state=q<HTMLElement>('[data-write-state]',root??document),meta=q<HTMLElement>('[data-write-meta]',root??document);if(!root||!state)return;state.className='signalState';state.innerHTML='<div><strong>글감을 정리하고 있어요</strong><p>원문과 수집 시각을 확인합니다.</p></div>';try{const r=await fetch(`/api/trends?ts=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error('데이터를 불러오지 못했어요.');const data=await r.json() as TrendData,items=Array.isArray(data.items)?data.items.filter(x=>x.url&&x.source_title).slice(0,3):[];if(!items.length)throw new Error('표시할 글감이 없어요.');drafts=items.map(makeDraft);const age=data.generated_at?Math.round((Date.now()-new Date(data.generated_at).getTime())/60000):null;if(meta)meta.textContent=`${age!==null&&age>180?'갱신 지연 · ':''}마지막 수집 ${d(data.generated_at)}`;state.className='signalGrid';state.innerHTML=items.map((x,i)=>`<article class="signalCard"><small>${e(x.community||'공개 커뮤니티')} · #${e(x.rank??i+1)}</small><h3>${e(x.source_title)}</h3><p>${e(cut(x.summary))}</p><div class="signalBox"><b>글 각도</b><p>${e(x.x_angle||x.topic||'원문 반응을 바탕으로 의견 묻기')}</p></div><div class="signalBox"><b>댓글 질문</b><p>${e(ask(x))}</p></div><div class="signalBox"><b>초안</b><p>${e(drafts[i])}</p></div><div class="signalActions"><button data-copy="${i}">초안 복사</button><a href="${e(x.url)}" target="_blank" rel="noreferrer">원문 링크 ↗</a></div></article>`).join('');writeReady=true}catch(err){if(meta)meta.textContent='연결 실패';state.className='signalState';state.innerHTML=`<div><strong>글감을 불러오지 못했어요</strong><p>${e(err instanceof Error?err.message:'다시 시도해 주세요.')}</p><button data-write-retry>다시 시도</button></div>`}}
async function copy(text:string){try{await navigator.clipboard.writeText(text)}catch{const a=document.createElement('textarea');a.value=text;a.style.position='fixed';a.style.opacity='0';document.body.appendChild(a);a.select();document.execCommand('copy');a.remove()}}
function writeClick(ev:Event){const x=ev.target as HTMLElement;if(x.closest('[data-write-retry]')){writeReady=false;void loadWrite(true);return}const b=x.closest<HTMLButtonElement>('[data-copy]');if(!b)return;const text=drafts[Number(b.dataset.copy)];if(!text)return;void copy(text).then(()=>{b.textContent='복사됨';setTimeout(()=>b.textContent='초안 복사',1400)})}
async function loadGlobal(force=false){if(globalReady&&!force)return;const root=q<HTMLElement>(`#${GLOBAL}`),state=q<HTMLElement>('[data-global-state]',root??document),meta=q<HTMLElement>('[data-global-meta]',root??document);if(!root||!state)return;state.className='signalState';state.innerHTML='<div><strong>최신 자료를 불러오고 있어요</strong><p>Hugging Face와 연결 중입니다.</p></div>';try{const r=await fetch('https://huggingface.co/api/daily_papers',{cache:'no-store'});if(!r.ok)throw new Error('Hugging Face 응답을 받지 못했어요.');const data=await r.json() as Daily[],papers=Array.isArray(data)?data.map(x=>x.paper??x).filter(x=>x.id&&x.title).slice(0,3):[];if(!papers.length)throw new Error('표시할 자료가 없어요.');if(meta)meta.textContent=`불러온 시각 ${d(new Date().toISOString())}`;state.className='signalGrid';state.innerHTML=papers.map(x=>`<article class="signalCard"><small>${e(x.organization?.fullname||x.organization?.name||'HUGGING FACE')}</small><h3>${e(x.title)}</h3><p>${e(cut(x.summary))}</p><div class="signalBox"><b>등록 시각</b><p>${d(x.publishedAt)}</p></div><div class="signalBox"><b>반응</b><p>추천 ${n(x.upvotes)} · 댓글 ${n(x.numComments)}</p></div><div class="signalActions"><a href="https://huggingface.co/papers/${e(x.id)}" target="_blank" rel="noreferrer">논문 보기 ↗</a>${x.githubRepo?`<a href="${e(x.githubRepo)}" target="_blank" rel="noreferrer">GitHub ↗</a>`:''}</div></article>`).join('');globalReady=true}catch(err){if(meta)meta.textContent='연결 실패';state.className='signalState';state.innerHTML=`<div><strong>글로벌 자료를 불러오지 못했어요</strong><p>${e(err instanceof Error?err.message:'다시 시도해 주세요.')}</p><button data-global-retry>다시 시도</button></div>`}}
function globalClick(ev:Event){if(!(ev.target as HTMLElement).closest('[data-global-retry]'))return;globalReady=false;void loadGlobal(true)}
function countRestoredVisit(){window.addEventListener('pageshow',ev=>{if(!ev.persisted)return;const key='luna-radar-visitor-session';let id=localStorage.getItem(key);if(!id){id=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`;localStorage.setItem(key,id)}void fetch('/api/visitor-stats',{method:'POST',headers:{'Content-Type':'application/json'},cache:'no-store',body:JSON.stringify({sessionId:id,event:'visit'})}).catch(()=>undefined)},{once:false})}
async function loadVisitors(){const bar=q<HTMLElement>(`#${VISITORS}`);if(!bar)return;try{const r=await fetch(`/api/visitor-stats?ts=${Date.now()}`,{cache:'no-store'}),x=await r.json() as Visitors;if(!r.ok||!x.available||x.active===null||x.today===null||x.total===null){bar.hidden=true;return}const a=q<HTMLElement>('[data-active]',bar),t=q<HTMLElement>('[data-today]',bar),z=q<HTMLElement>('[data-total]',bar);if(a)a.textContent=`${n(x.active)}명`;if(t)t.textContent=`오늘 ${n(x.today)}회 · 누적 방문`;if(z)z.textContent=`${n(x.total)}회`;bar.hidden=false}catch{bar.hidden=true}}
let restoredVisitBound=false;
function mount(){if(!restoredVisitBound){restoredVisitBound=true;countRestoredVisit()}const main=q<HTMLElement>('main.page'),heroGrid=q<HTMLElement>('.heroGrid',main??document);if(!main||!heroGrid)return false;styles();hero(main);const top=tabNav(heroGrid);custom(top);visitor(heroGrid);classify(main);show(active,false);setTimeout(()=>void loadVisitors(),800);if(timer===null)timer=window.setInterval(()=>void loadVisitors(),30000);if(!watcher){watcher=new MutationObserver(()=>{if(busy)return;busy=true;requestAnimationFrame(()=>{busy=false;mount()})});watcher.observe(document.body,{childList:true,subtree:true})}return true}
if(!mount()){const boot=new MutationObserver(()=>{if(!mount())return;boot.disconnect()});boot.observe(document.documentElement,{childList:true,subtree:true})}
